# Generated by Django 5.1.2 on 2024-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'creador'), ('admin', 'Administrador')], default='creator', max_length=10),
        ),
    ]
