# Generated by Django 5.1.2 on 2024-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Creador'), ('admin', 'Administrador')], default='creator', max_length=10),
        ),
    ]
