# Generated by Django 5.1.2 on 2025-01-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_created_at_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('prefer_not_to_say', 'Prefiero no decirlo')], max_length=20, null=True),
        ),
    ]
