# Generated by Django 5.1.2 on 2025-01-16 15:06

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=users.models.generate_random_id, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
