# Generated by Django 5.1.2 on 2025-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ubication',
            field=models.CharField(blank=True, choices=[('sl', 'San Luis'), ('ip', 'Ipala')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('invited', 'Invitado'), ('creator', 'Creador'), ('admin', 'Administrador')], default='creator', max_length=10),
        ),
    ]
