# Generated by Django 5.1.2 on 2025-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_ubication_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ubication',
            field=models.CharField(blank=True, choices=[('sl', 'San Luis'), ('ip', 'Ipala')], default='sl', max_length=255, null=True),
        ),
    ]
