# Generated by Django 5.1.2 on 2025-01-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='Organizacion', max_length=255),
        ),
    ]
