# Generated by Django 5.1.2 on 2025-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
