# Generated by Django 5.1.2 on 2025-01-16 14:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_configuration_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['user'], name='private_use_user_id_d23874_idx'),
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['timestamp'], name='private_use_timesta_f2b520_idx'),
        ),
    ]
