# Generated by Django 5.1.2 on 2025-01-22 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0005_alter_configuration_banner_alter_configuration_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
    ]
