# Generated by Django 5.1.2 on 2025-04-05 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0006_alter_configuration_banner_alter_configuration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
    ]
