# Generated by Django 5.1.2 on 2025-10-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0007_configuration_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
