# Generated by Django 5.1.2 on 2025-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0008_configuration_direction_configuration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='footer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='gratitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
