# Generated by Django 5.1.2 on 2025-06-01 16:52

import django.db.models.deletion
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('phone', models.IntegerField(blank=True, null=True, validators=[employee.models.validate_eight_digits])),
                ('is_working', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('atencion', 'Atención al Cliente'), ('costura', 'Costura y Confección'), ('impresion', 'Impresión'), ('sublimacion', 'Sublimación')], default='atencion', max_length=20)),
                ('ubication', models.CharField(choices=[('sl', 'San Luis'), ('ip', 'Ipala')], default='sl', max_length=20)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('mount', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
