# Generated by Django 5.1.2 on 2025-07-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_created_at_client_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
