# Generated by Django 5.1.2 on 2025-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_created_at_client_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
