# Generated by Django 5.0.3 on 2025-04-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0002_client_remove_order_customer_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
