# Generated by Django 5.1.2 on 2025-06-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_created_at_client_updated_at_and_more'),
        ('orders', '0006_order_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client'),
        ),
    ]
