# Generated by Django 5.1.2 on 2025-07-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('recibido', 'Recibido'), ('diseno', 'Diseño'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Clase del ícono de Bootstrap, por ejemplo: 'bi bi-box-seam'", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus'),
        ),
    ]
