# Generated by Django 5.1.2 on 2025-10-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus'),
        ),
    ]
