# Generated by Django 5.1.2 on 2025-01-16 20:55

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(max_length=100, verbose_name='Tela')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('stock', models.PositiveIntegerField(verbose_name='Inventario disponible')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, verbose_name='Talla')),
                ('color', models.CharField(choices=[('white', 'Blanco'), ('black', 'Negro'), ('red', 'Rojo'), ('blue', 'Azul'), ('green', 'Verde')], max_length=20, verbose_name='Color')),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='tshirts/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Playera',
                'verbose_name_plural': 'Playeras',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.CharField(default=products.models.generate_random_id, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='Diseño')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tags', models.ManyToManyField(blank=True, related_name='tshirts', to='products.tag', verbose_name='Categorias')),
            ],
        ),
    ]
