# Generated by Django 5.1.2 on 2025-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=160, max_digits=10, verbose_name='Precio de venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='on_offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
