# Generated by Django 5.1.2 on 2025-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_design_offer_price_design_on_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de oferta'),
        ),
        migrations.AlterField(
            model_name='design',
            name='on_offer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='En Oferta'),
        ),
    ]
