# Generated by Django 5.1.2 on 2025-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_design_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre'),
        ),
    ]
