# Generated by Django 5.1.2 on 2025-03-05 16:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_design_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='public',
            field=models.CharField(default=products.models.generate_random_id, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
